
//Power Plants vs. Diseases - US Data Exploration viz

var onedElement = document.getElementById('viz1682822400844');                    
var onevElement = onedElement.getElementsByTagName('object')[0];                    
if ( onedElement.offsetWidth > 800 ) { onevElement.style.width='960px';onevElement.style.height='607px';} else if ( onedElement.offsetWidth > 500 ) { onevElement.style.width='960px';onevElement.style.height='607px';} else { onevElement.style.width='100%';onevElement.style.height='727px';}                     
var scriptElement = document.createElement('script');                    
scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    
onevElement.parentNode.insertBefore(scriptElement, onevElement);  



 /// Cancer Rates vs. Distance - US Data Exploration
var twodElement = document.getElementById('viz1682824906117');                    var twovElement = twodElement.getElementsByTagName('object')[0];                    if ( twodElement.offsetWidth > 800 ) { twovElement.style.width='960px';twovElement.style.height='567px';} else if ( twodElement.offsetWidth > 500 ) { twovElement.style.width='960px';twovElement.style.height='567px';} else { twovElement.style.width='100%';twovElement.style.height='777px';}                     var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    twovElement.parentNode.insertBefore(scriptElement, twovElement);     

// Disease vs. Pollution Metrics - US Data Exploration

var threedElement = document.getElementById('viz1682825210977');                    var threevElement = threedElement.getElementsByTagName('object')[0];                    if ( threedElement.offsetWidth > 800 ) { threevElement.style.width='960px';threevElement.style.height='607px';} else if ( threedElement.offsetWidth > 500 ) { threevElement.style.width='960px';threevElement.style.height='607px';} else { threevElement.style.width='100%';threevElement.style.height='727px';}                     var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    threevElement.parentNode.insertBefore(scriptElement, threevElement);     


 var sevendElement = document.getElementById('viz1682822398346');                    var sevenvElement = sevendElement.getElementsByTagName('object')[0];                    if ( sevendElement.offsetWidth > 800 ) { sevenvElement.style.width='960px';sevenvElement.style.height='607px';} else if ( sevendElement.offsetWidth > 500 ) { sevenvElement.style.width='960px';sevenvElement.style.height='607px';} else { sevenvElement.style.width='100%';sevenvElement.style.height='727px';}                     var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    sevenvElement.parentNode.insertBefore(scriptElement, sevenvElement);                












































































































